import { describe, expect, it } from 'vitest'
import { isLegacyPasswordHash, verifyLegacyPassword } from '../../server/utils/legacy-password'

// Hash generated by the OLD app's own hash_password() (app/main.py:444-449,
// hashlib.pbkdf2_hmac('sha256', ..., 600_000 iterations)) for the password
// "correct horse" -- a real cross-implementation golden fixture, not a
// hand-derived one, matching this project's reproduce-old-behavior stance.
const GOLDEN_LEGACY_HASH =
  'pbkdf2_sha256$600000$aabbccddeeff00112233445566778899$2827fa3f613ab847349f9a4883541ee49b590842ba3e13708d4af92af3f9dfd9'

describe('legacy password compat (old app pbkdf2_sha256 format)', () => {
  it('identifies a legacy hash by its prefix', () => {
    expect(isLegacyPasswordHash(GOLDEN_LEGACY_HASH)).toBe(true)
    expect(isLegacyPasswordHash('$scrypt$...')).toBe(false)
  })

  it('verifies the correct password against a real old-app-generated hash', () => {
    expect(verifyLegacyPassword(GOLDEN_LEGACY_HASH, 'correct horse')).toBe(true)
  })

  it('rejects the wrong password', () => {
    expect(verifyLegacyPassword(GOLDEN_LEGACY_HASH, 'wrong password')).toBe(false)
  })

  it('rejects a malformed hash instead of throwing', () => {
    expect(verifyLegacyPassword('not-a-real-hash', 'anything')).toBe(false)
    expect(verifyLegacyPassword('pbkdf2_sha256$notanumber$aa$bb', 'anything')).toBe(false)
  })
})
